# Netlify CMS 配置文件 - 简化版
# 保存为: public/admin/config.yml

backend:
  name: git-gateway
  branch: main

media_folder: public/images/uploads
public_folder: /images/uploads

collections:
  # 新闻管理
  - name: "news"
    label: "新闻动态"
    folder: "content/news"
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    fields:
      - { label: "标题", name: "title", widget: "string" }
      - { label: "发布日期", name: "date", widget: "datetime" }
      - { label: "分类", name: "category", widget: "select", options: ["公司动态", "市场分析", "行业洞察"] }
      - { label: "摘要", name: "summary", widget: "text" }
      - { label: "特色图片", name: "featuredImage", widget: "image", required: false }
      - { label: "内容", name: "body", widget: "markdown" }
      - { label: "状态", name: "status", widget: "select", options: ["草稿", "已发布"], default: "草稿" }

  # 服务管理
  - name: "services"
    label: "服务内容"
    folder: "content/services"
    create: true
    slug: "{{slug}}"
    fields:
      - { label: "服务名称", name: "title", widget: "string" }
      - { label: "图标", name: "icon", widget: "string", hint: "输入emoji或图标类名" }
      - { label: "状态", name: "status", widget: "select", options: ["进行中", "规划中", "已完成"] }
      - { label: "简短描述", name: "description", widget: "text" }
      - { label: "详细介绍", name: "body", widget: "markdown" }
      - { label: "服务特点", name: "features", widget: "list" }
      - { label: "服务优势", name: "advantages", widget: "list" }
      - { label: "排序权重", name: "order", widget: "number", default: 0 }

  # 公司信息
  - name: "company"
    label: "公司信息"
    files:
      - label: "基本信息"
        name: "basic_info"
        file: "content/company/basic-info.md"
        fields:
          - { label: "公司名称", name: "company_name", widget: "string" }
          - { label: "英文名称", name: "english_name", widget: "string" }
          - { label: "成立年份", name: "established_year", widget: "string" }
          - { label: "总部位置", name: "headquarters", widget: "string" }
          - { label: "主营业务", name: "main_business", widget: "string" }
          - { label: "公司简介", name: "description", widget: "markdown" }
          - { label: "企业愿景", name: "vision", widget: "text" }
          - { label: "企业使命", name: "mission", widget: "text" }
          - { label: "核心价值观", name: "values", widget: "list" }
          - { label: "公司Logo", name: "logo", widget: "image" }

  # 联系信息
  - name: "contact"
    label: "联系方式"
    files:
      - label: "联系信息"
        name: "contact_info"
        file: "content/contact/info.md"
        fields:
          - { label: "邮箱地址", name: "email", widget: "string" }
          - { label: "电话号码", name: "phone", widget: "string" }
          - { label: "传真号码", name: "fax", widget: "string", required: false }
          - { label: "详细地址", name: "address", widget: "text" }
          - { label: "营业时间", name: "business_hours", widget: "string" }
          - { label: "微信号", name: "wechat", widget: "string", required: false }
          - { label: "LinkedIn", name: "linkedin", widget: "string", required: false }