# public/admin/config.yml - 完善版本
backend:
  name: git-gateway
  branch: main

media_folder: public/images/uploads
public_folder: /images/uploads

# 站点URL配置
site_url: https://steady-clafoutis-c30c37.netlify.app
display_url: https://steady-clafoutis-c30c37.netlify.app

# 发布模式
publish_mode: editorial_workflow

# 国际化设置
i18n:
  structure: multiple_files
  locales: [zh, ja, en]
  default_locale: zh

collections:
  # 新闻管理（已有，增强版）
  - name: "news"
    label: "新闻动态"
    folder: "content/news"
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    editor:
      preview: true
    fields:
      - { label: "标题", name: "title", widget: "string", required: true }
      - { label: "发布日期", name: "date", widget: "datetime", default: "" }
      - { label: "分类", name: "category", widget: "select", options: ["公司动态", "市场分析", "行业洞察"], required: true }
      - { label: "摘要", name: "summary", widget: "text", required: true }
      - { label: "特色图片", name: "featuredImage", widget: "image", required: false }
      - { label: "内容", name: "body", widget: "markdown", required: true }
      - { label: "状态", name: "status", widget: "select", options: ["草稿", "已发布"], default: "草稿" }
      - { label: "作者", name: "author", widget: "string", default: "岩林株式会社" }
      - { label: "关键词", name: "keywords", widget: "string", required: false, hint: "用逗号分隔" }
      - { label: "标签", name: "tags", widget: "list", required: false, field: { label: "标签", name: "tag", widget: "string" } }

  # 公司信息管理（增强版）
  - name: "company"
    label: "公司信息"
    files:
      - label: "基本信息"
        name: "basic_info"
        file: "content/company/basic-info.md"
        fields:
          - { label: "公司中文名称", name: "company_name", widget: "string", default: "岩林株式会社" }
          - { label: "公司英文名称", name: "english_name", widget: "string", default: "IWABAYASHI Corporation" }
          - { label: "成立年份", name: "established_year", widget: "string", default: "2025" }
          - { label: "总部位置", name: "headquarters", widget: "string", default: "日本东京" }
          - { label: "主营业务", name: "main_business", widget: "string" }
          - { label: "企业愿景", name: "vision", widget: "text" }
          - { label: "企业使命", name: "mission", widget: "text" }
          - { label: "核心价值观", name: "values", widget: "list", field: { label: "价值观", name: "value", widget: "string" } }
          - { label: "员工人数", name: "employee_count", widget: "string", default: "20-50人" }
          - { label: "注册资本", name: "registered_capital", widget: "string", default: "1000万日元" }
          - { label: "公司Logo", name: "logo", widget: "image", required: false }
          - { label: "详细介绍", name: "body", widget: "markdown" }

      - label: "团队成员"
        name: "team_members"
        file: "content/company/team-members.md"
        fields:
          - label: "团队成员列表"
            name: "members"
            widget: "list"
            fields:
              - { label: "姓名", name: "name", widget: "string" }
              - { label: "职位", name: "position", widget: "string" }
              - { label: "头像", name: "avatar", widget: "image", required: false }
              - { label: "简介", name: "bio", widget: "text" }
              - { label: "邮箱", name: "email", widget: "string", required: false }
              - { label: "LinkedIn", name: "linkedin", widget: "string", required: false }
              - { label: "排序", name: "order", widget: "number", default: 0 }

  # 服务内容管理（新增）
  - name: "services"
    label: "服务内容"
    folder: "content/services"
    create: true
    slug: "{{slug}}"
    fields:
      - { label: "服务名称", name: "title", widget: "string" }
      - { label: "服务类型", name: "type", widget: "select", options: ["进行中", "规划中", "已完成"] }
      - { label: "图标", name: "icon", widget: "string", hint: "输入emoji或图标类名" }
      - { label: "简短描述", name: "description", widget: "text" }
      - { label: "详细介绍", name: "body", widget: "markdown" }
      - label: "服务特点"
        name: "features"
        widget: "list"
        field: { label: "特点", name: "feature", widget: "string" }
      - label: "服务优势"
        name: "advantages"
        widget: "list"
        field: { label: "优势", name: "advantage", widget: "string" }
      - label: "服务流程"
        name: "process"
        widget: "list"
        fields:
          - { label: "步骤号", name: "step", widget: "number" }
          - { label: "步骤名称", name: "title", widget: "string" }
          - { label: "步骤描述", name: "description", widget: "text" }
      - { label: "排序权重", name: "order", widget: "number", default: 0 }
      - { label: "启用状态", name: "enabled", widget: "boolean", default: true }

  # 首页内容管理（新增）
  - name: "homepage"
    label: "首页内容"
    files:
      - label: "首页配置"
        name: "home_content"
        file: "content/pages/home-content.md"
        fields:
          - label: "Hero区域"
            name: "hero"
            widget: "object"
            fields:
              - { label: "主标语", name: "slogan", widget: "string" }
              - { label: "副标语", name: "subtitle", widget: "string" }
              - { label: "描述", name: "description", widget: "text" }
              - { label: "背景视频", name: "background_video", widget: "file", required: false }
              - { label: "背景图片", name: "background_image", widget: "image", required: false }
              - label: "特色标签"
                name: "features"
                widget: "list"
                field: { label: "特色", name: "feature", widget: "string" }

  # 联系信息管理（增强版）
  - name: "contact"
    label: "联系方式"
    files:
      - label: "联系信息"
        name: "contact_info"
        file: "content/contact/info.md"
        fields:
          - { label: "主邮箱地址", name: "email", widget: "string" }
          - { label: "客服邮箱", name: "support_email", widget: "string", required: false }
          - { label: "办公电话", name: "phone", widget: "string" }
          - { label: "传真号码", name: "fax", widget: "string", required: false }
          - { label: "紧急联系电话", name: "emergency_phone", widget: "string", required: false }
          - { label: "详细地址（中文）", name: "address", widget: "text" }
          - { label: "详细地址（日文）", name: "address_ja", widget: "text", required: false }
          - { label: "营业时间", name: "business_hours", widget: "string" }
          - { label: "网站地址", name: "website", widget: "string" }
          - { label: "微信号", name: "wechat", widget: "string", required: false }
          - { label: "LinkedIn", name: "linkedin", widget: "string", required: false }
          
          - label: "交通信息"
            name: "transportation"
            widget: "list"
            field: { label: "交通路线", name: "route", widget: "string" }
          
          - label: "办公室信息"
            name: "office_info"
            widget: "object"
            fields:
              - { label: "楼层", name: "floor", widget: "string" }
              - { label: "房间号", name: "room", widget: "string", required: false }
              - { label: "邮政编码", name: "postal_code", widget: "string" }
              - { label: "附近地标", name: "landmarks", widget: "string", required: false }

  # 页脚内容管理（新增）
  - name: "footer"
    label: "页脚内容"
    files:
      - label: "页脚配置"
        name: "footer_content"
        file: "content/pages/footer-content.md"
        fields:
          - { label: "公司描述", name: "description", widget: "text" }
          - label: "业务内容"
            name: "business_items"
            widget: "list"
            field: { label: "业务项目", name: "item", widget: "string" }
          - label: "快速链接"
            name: "quick_links"
            widget: "list"
            fields:
              - { label: "链接名称", name: "name", widget: "string" }
              - { label: "链接地址", name: "url", widget: "string" }
              - { label: "是否外部链接", name: "external", widget: "boolean", default: false }
          - label: "社交媒体"
            name: "social_media"
            widget: "list"
            fields:
              - { label: "平台名称", name: "platform", widget: "string" }
              - { label: "链接地址", name: "url", widget: "string" }
              - { label: "图标", name: "icon", widget: "string" }
          - { label: "版权信息", name: "copyright", widget: "string" }
          - { label: "备案信息", name: "filing_info", widget: "string", required: false }

  # 多语言翻译管理（新增）
  - name: "translations"
    label: "多语言翻译"
    files:
        - label: "中文翻译"
          name: "zh_translations"
          file: "src/i18n/resources/zh/cms.json"
          fields:
            - label: "导航菜单"
            name: "navigation"
            widget: "object"
            fields:
              - { label: "首页", name: "home", widget: "string", default: "首页" }
              - { label: "关于我们", name: "about", widget: "string", default: "关于我们" }
              - { label: "服务内容", name: "services", widget: "string", default: "服务内容" }
              - { label: "新闻动态", name: "news", widget: "string", default: "新闻动态" }
              - { label: "联系我们", name: "contact", widget: "string", default: "联系我们" }

            - label: "页面标题"
              name: "pageTitle"
              widget: "object"
              fields:
                - { label: "关于我们", name: "about", widget: "string", default: "关于我们" }
                - { label: "服务内容", name: "services", widget: "string", default: "服务内容" }
                - { label: "新闻动态", name: "news", widget: "string", default: "新闻动态" }
                - { label: "联系我们", name: "contact", widget: "string", default: "联系我们" }

            - label: "页脚"
              name: "footer"
              widget: "object"
              fields:
                - { label: "快速链接", name: "quickLinks", widget: "string", default: "快速链接" }
                - { label: "联系方式", name: "contact", widget: "string", default: "联系方式" }
                - { label: "业务内容", name: "business", widget: "string", default: "业务内容" }
                - label: "联系方式子项"
                  name: "contactItems"
                  widget: "object"
                  fields:
                    - { label: "邮箱", name: "email", widget: "string", default: "邮箱" }
                    - { label: "电话", name: "phone", widget: "string", default: "电话" }
                    - { label: "地址", name: "address", widget: "string", default: "地址" }
                    - { label: "营业时间", name: "hours", widget: "string", default: "营业时间" }
                - label: "底部链接"
                  name: "links"
                  widget: "object"
                  fields:
                    - { label: "隐私政策", name: "privacy", widget: "string", default: "隐私政策" }
                    - { label: "使用条款", name: "terms", widget: "string", default: "使用条款" }
                    - { label: "网站地图", name: "sitemap", widget: "string", default: "网站地图" }
                - { label: "标语", name: "tagline", widget: "string", default: "专业的中日贸易综合服务商" }
                - { label: "版权后缀", name: "builtWith", widget: "string", default: "Built with ❤️ for connecting China and Japan" }

        - label: "日语翻译"
          name: "ja_translations"
          file: "src/i18n/resources/ja/cms.json"
          fields:
            - label: "導航メニュー"
            name: "navigation"
            widget: "object"
            fields:
              - { label: "ホーム", name: "home", widget: "string", default: "ホーム" }
              - { label: "会社概要", name: "about", widget: "string", default: "会社概要" }
              - { label: "事業内容", name: "services", widget: "string", default: "事業内容" }
              - { label: "ニュース", name: "news", widget: "string", default: "ニュース" }
              - { label: "お問い合わせ", name: "contact", widget: "string", default: "お問い合わせ" }

            - label: "ページタイトル"
              name: "pageTitle"
              widget: "object"
              fields:
                - { label: "会社概要", name: "about", widget: "string", default: "会社概要" }
                - { label: "事業内容", name: "services", widget: "string", default: "事業内容" }
                - { label: "ニュース", name: "news", widget: "string", default: "ニュース" }
                - { label: "お問い合わせ", name: "contact", widget: "string", default: "お問い合わせ" }

            - label: "フッター"
              name: "footer"
              widget: "object"
              fields:
                - { label: "クイックリンク", name: "quickLinks", widget: "string", default: "クイックリンク" }
                - { label: "連絡先", name: "contact", widget: "string", default: "連絡先" }
                - { label: "事業内容", name: "business", widget: "string", default: "事業内容" }
                - label: "連絡項目"
                  name: "contactItems"
                  widget: "object"
                  fields:
                    - { label: "メール", name: "email", widget: "string", default: "メール" }
                    - { label: "電話", name: "phone", widget: "string", default: "電話" }
                    - { label: "住所", name: "address", widget: "string", default: "住所" }
                    - { label: "営業時間", name: "hours", widget: "string", default: "営業時間" }
                - label: "リンク"
                  name: "links"
                  widget: "object"
                  fields:
                    - { label: "プライバシー", name: "privacy", widget: "string", default: "プライバシーポリシー" }
                    - { label: "利用規約", name: "terms", widget: "string", default: "利用規約" }
                    - { label: "サイトマップ", name: "sitemap", widget: "string", default: "サイトマップ" }
                - { label: "タグライン", name: "tagline", widget: "string", default: "日中貿易の総合サービスプロバイダー" }
                - { label: "ビルド情報", name: "builtWith", widget: "string", default: "Built with ❤️ for connecting China and Japan" }

        - label: "英语翻译"
          name: "en_translations"
          file: "src/i18n/resources/en/cms.json"
          fields:
            - label: "Navigation Menu"
            name: "navigation"
            widget: "object"
            fields:
              - { label: "Home", name: "home", widget: "string", default: "Home" }
              - { label: "About", name: "about", widget: "string", default: "About Us" }
              - { label: "Services", name: "services", widget: "string", default: "Services" }
              - { label: "News", name: "news", widget: "string", default: "News" }
              - { label: "Contact", name: "contact", widget: "string", default: "Contact" }

            - label: "Page Titles"
              name: "pageTitle"
              widget: "object"
              fields:
                - { label: "About", name: "about", widget: "string", default: "About Us" }
                - { label: "Services", name: "services", widget: "string", default: "Services" }
                - { label: "News", name: "news", widget: "string", default: "News" }
                - { label: "Contact", name: "contact", widget: "string", default: "Contact" }

            - label: "Footer"
              name: "footer"
              widget: "object"
              fields:
                - { label: "Quick Links", name: "quickLinks", widget: "string", default: "Quick Links" }
                - { label: "Contact Section", name: "contact", widget: "string", default: "Contact Information" }
                - { label: "Business Section", name: "business", widget: "string", default: "Business Services" }
                - label: "Contact Items"
                  name: "contactItems"
                  widget: "object"
                  fields:
                    - { label: "Email", name: "email", widget: "string", default: "Email" }
                    - { label: "Phone", name: "phone", widget: "string", default: "Phone" }
                    - { label: "Address", name: "address", widget: "string", default: "Address" }
                    - { label: "Hours", name: "hours", widget: "string", default: "Business Hours" }
                - label: "Legal Links"
                  name: "links"
                  widget: "object"
                  fields:
                    - { label: "Privacy", name: "privacy", widget: "string", default: "Privacy Policy" }
                    - { label: "Terms", name: "terms", widget: "string", default: "Terms of Service" }
                    - { label: "Sitemap", name: "sitemap", widget: "string", default: "Sitemap" }
                - { label: "Tagline", name: "tagline", widget: "string", default: "Professional China-Japan Trade Service Provider" }
                - { label: "Built With", name: "builtWith", widget: "string", default: "Built with ❤️ for connecting China and Japan" }
